name: FancyGenerators
main: surva\fancygenerators\FancyGenerators
version: 1.2.0
api: 5.0.0

author: survanetwork
description: A collection of new level Generators
website: https://plugins.surva.net/#fancygenerators
